name: Sync Blogs
on:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC 0点（北京时间8点）运行
jobs:
  sync-csdn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install requests beautifulsoup4
        python scripts/csdn_sync.py
    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add ./assets/blogs
        git commit -m "Auto sync blogs"
        git push
